- headers:
    user-agent: fetch-synthetic-monitor
  method: GET
  name: fetch index page
  url: https://google.com/
- headers:
    user-agent: fetch-synthetic-monitor
  method: GET
  name: fetch careers page
  url: https://google.com/
