- headers:
    user-agent: fetch-synthetic-monitor
  method: GET
  name: fetch index
  url: https://fetch.com/
- headers:
    user-agent: fetch-synthetic-monitor
  method: GET
  name: fetch careers
  url: https://fetch.com/careers
- headers:
    user-agent: fetch-synthetic-monitor
  method: GET
  name: google homepage
  url: https://www.google.com/
- headers:
    user-agent: fetch-synthetic-monitor
  method: GET
  name: GitHub homepage
  url: https://github.com/
- headers:
    user-agent: fetch-synthetic-monitor
  method: GET
  name: Reddit homepage
  url: https://www.reddit.com/
